# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# reclass.py
# Created on: 2016-09-26 15:19:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: reclass <LE72020322012003EDC00_B1_TIF> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, arcinfo, os, re
from arcpy.sa import *

arcpy.AddMessage(arcpy.CheckExtension("Spatial"))
# recorremos todos los rasters de cada directorio
path = r'Z:\Proyectos\marina_valdecanas\capas\teledeteccion\Landsat\ori'

for i in os.listdir(path):

	npath = os.path.join(path, i)
	if os.path.isdir(npath) and re.search('^[0-9]', i):

		print(i)

		for r in os.listdir(npath):

			if not 'l8oli' in r:

				bandas = ['B1.TIF', 'B2.TIF', 'B3.TIF', 'B4.TIF', 'B5.TIF', 'B7.TIF']

			else:

				bandas = ['B2.TIF', 'B3.TIF', 'B4.TIF', 'B5.TIF', 'B6.TIF', 'B7.TIF']

			banda = r[-6:]

			if banda in bandas:

				print(banda)
				# Local variables:
				raster = os.path.join(npath, r)
				true = "0"
				false = "1"
				Con_TIF2 = r'Z:\Proyectos\marina_valdecanas\capas\teledeteccion\Landsat\extent\{}'.format(r)

				# Process: Con
				arcpy.gp.Con_sa(raster, true, Con_TIF2, false, "\"Value\" = 0")

