# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# smooth.py
# Created on: 2016-11-23 15:13:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arcpy, os

arcpy.env.overwriteOutput = True
# Local variables:
rutapro = r'H:\VDCNS\protocolo\pro'

for i in os.listdir(rutapro):

	if os.path.isdir(os.path.join(rutapro, i)):
		#print i

		escena = os.path.join(rutapro, i)
		for s in os.listdir(escena):
			
			if s.endswith('contour.shp'):
				print s
				
				try:


					# Local variables:
					contour = os.path.join(escena, s)
					out_contour = os.path.join(escena, 'smooth_' + os.path.split(contour)[1])
					print out_contour

					# Process: Smooth Line
					arcpy.SmoothLine_cartography(contour, out_contour, "PAEK", "100 Meters", "FIXED_CLOSED_ENDPOINT", "NO_CHECK")


				except Exception as e:
					print 'Error', e
					continue